#!/bin/bash
# Test RC Loss Failsafe
# Simulate loss of RC link

echo "=========================================="
echo "RC Loss Failsafe Test"
echo "=========================================="
echo ""
echo "Test Procedure:"
echo "=================="
echo "1. Arm drone with RC (or simulated RC)"
echo "2. Takeoff and switch to mission/offboard mode"
echo "3. Simulate RC signal loss"
echo "4. Observe failsafe behavior"
echo ""
echo "Expected Behavior (depends on mode):"
echo "  - In Manual/Stabilized: RTL or Land"
echo "  - In Mission/Offboard: Continue or RTL based on COM_RCL_EXCEPT"
echo ""
echo "Key Parameters:"
echo "---------------"
echo "  COM_RC_LOSS_T    - RC loss timeout (default 0.5s)"
echo "  COM_RCL_EXCEPT   - RC loss exceptions (modes that can continue)"
echo "  NAV_RCL_ACT      - RC loss action (0=Disabled, 1=Hold, 2=RTL, 3=Land, 5=Terminate)"
echo ""
echo "Test Command:"
echo "-------------"
echo "# For Gazebo Harmonic SITL, RC is usually not used"
echo "# If using virtual RC, you can test by:"
echo ""
echo "1. Check current RC status:"
echo "   listener manual_control_setpoint"
echo ""
echo "2. Verify RC loss detection:"
echo "   # In PX4 console"
echo "   param set COM_RC_LOSS_T 0.5"
echo "   # Stop publishing RC commands"
echo ""
echo "Note: In most SITL setups, RC is not active by default."
echo "Consider testing with QGC joystick, then disconnecting."
echo ""
