#!/bin/bash
# Test Battery Low Failsafe
# Simulate low battery condition

echo "=========================================="
echo "Battery Low Failsafe Test"
echo "=========================================="
echo ""
echo "Test Procedure:"
echo "=================="
echo "1. Arm and takeoff drone"
echo "2. Simulate battery drain to trigger low battery warning"
echo "3. Observe RTL behavior"
echo ""
echo "Expected Behavior:"
echo "  - Battery > warning level: Normal operation"
echo "  - Battery < warning level: RTL initiated"
echo "  - Battery < critical level: Immediate land"
echo ""
echo "Key Parameters:"
echo "---------------"
echo "  BAT_CRIT_THR  - Critical battery threshold (default 0.07 = 7%)"
echo "  BAT_LOW_THR   - Low battery threshold (default 0.15 = 15%)"
echo "  BAT_EMERGEN_THR - Emergency threshold (default 0.05 = 5%)"
echo "  COM_LOW_BAT_ACT - Low battery action (0=Warning, 1=RTL, 2=Land)"
echo ""
echo "Method 1: Via Parameter Override (Simulation)"
echo "----------------------------------------------"
echo "In QGC or PX4 console, set low threshold to trigger immediately:"
echo "  param set BAT_LOW_THR 0.95    # Trigger at 95% (simulated)"
echo "  param set COM_LOW_BAT_ACT 1   # Action: RTL"
echo ""
echo "Method 2: Via Battery Publication (ROS 2)"
echo "------------------------------------------"
echo "Publish low battery status via ROS 2:"
echo "  ros2 topic pub /fmu/in/battery_status px4_msgs/msg/BatteryStatus '{remaining: 0.1}'"
echo ""
echo "Method 3: Monitor Natural Drain"
echo "--------------------------------"
echo "Let simulation run and battery will naturally drain based on:"
echo "  SIM_BAT_DRAIN - Battery consumption rate"
echo ""
