#!/bin/bash
# Test Datalink (Telemetry) Loss Failsafe
# Simulate loss of ground station connection

echo "=========================================="
echo "Datalink Loss Failsafe Test"
echo "=========================================="
echo ""
echo "Test Procedure:"
echo "=================="
echo "1. Connect QGC to drone"
echo "2. Arm and start mission"
echo "3. Close QGC or block MAVLink port"
echo "4. Observe failsafe after timeout"
echo ""
echo "Expected Behavior:"
echo "  - Datalink active: Normal operation"
echo "  - Datalink lost > timeout: RTL or configured action"
echo ""
echo "Key Parameters:"
echo "---------------"
echo "  COM_DL_LOSS_T    - Datalink loss timeout (default 10s)"
echo "  NAV_DLL_ACT      - Datalink loss action (0=Disabled, 1=Hold, 2=RTL, 3=Land, 5=Terminate)"
echo "  COM_DL_REG_T     - Datalink regain timeout"
echo ""
echo "Test Methods:"
echo "-------------"
echo ""
echo "Method 1: Close QGroundControl"
echo "  1. Start mission with QGC connected"
echo "  2. Close QGC application"
echo "  3. Wait for COM_DL_LOSS_T seconds"
echo "  4. Observe drone executing NAV_DLL_ACT"
echo ""
echo "Method 2: Block MAVLink Port"
echo "  sudo iptables -A INPUT -p udp --dport 14540 -j DROP"
echo "  # Wait for timeout"
echo "  sudo iptables -D INPUT -p udp --dport 14540 -j DROP"
echo ""
echo "Method 3: Kill MAVLink Bridge (ROS 2)"
echo "  pkill -f micro_ros_agent"
echo "  # Drone should detect loss after timeout"
echo ""
echo "Recommended Settings for Testing:"
echo "----------------------------------"
echo "  param set COM_DL_LOSS_T 5      # 5 second timeout (faster testing)"
echo "  param set NAV_DLL_ACT 2        # RTL on datalink loss"
echo ""
