#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=dronex}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=warehouse}

param set-default SIM_GZ_EN 1
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2

param set-default SENS_IMU_MODE 0  # Enables simulation mode for IMU (accel + gyro); default may be hardware mode.
param set-default SENS_EN_GPSSIM 1  # Enables simulated GPS.
param set-default SENS_EN_BAROSIM 1  # Enables simulated barometer.
param set-default SENS_EN_MAGSIM 1  # Enables simulated magnetometer (compass).
# param set-default SIM_BARO_DIS 0  # Ensures barometer data is not disabled.
# param set-default EKF2_REQ_GPS_H 0.5  # Lowers GPS height requirement if needed for arming (adjust based on sim).

param set SYS_HAS_MAG 1
param set SDLOG_MODE 0
param set SDLOG_PROFILE 2

param set EKF2_MULTI_IMU = 0
param set EKF2_MULTI_MAG = 0
param set COM_OF_LOSS_T 60
param set COM_OBL_RC_ACT 2


